name: Checkout
on: push
jobs:
  checkout:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master
        with:
          ref: 'main'

      - uses: actions/checkout@master
        with:
          ref: 'main'
          repository: wnynya/Wanyne-config
          token: ${{ secrets.CONFIG_TOKEN }}
          path: './config'

      - run: npm cache clean --force

      - run: npm install

      - run: ./start.sh
